Enable frontier wallet injected connector option
family/connectkit pull request #257
Opened 2023-07-03 11:13 UTC by akash-frontier

2023-07-17 13:22 UTC, lochie requested changes
There's a check in this PR that isn't necessary, I'd suggest removing it.

@akash-frontier could you also merge the latest in from `main`. We will happily merge this in once that's done. Thanks!

2023-07-17 13:22 UTC, lochie commented on packages/connectkit/src/components/Pages/Connectors/index.tsx
> +      isFrontier();
This check here isn't necessary.

2023-07-18 10:09 UTC, akash-frontier commented
Hi @lochie, I've resolved the conflicts in the pull request. Please review it when you have the time. Thank you!

2023-07-19 02:51 UTC, lochie approved these changes

2023-07-19 02:53 UTC, merged

2023-07-19 02:53 UTC, lochie commented
merged, thanks @akash-frontier!