return promise from siweConfig.createMessage
family/connectkit pull request #324
Opened 2023-11-28 08:15 UTC by anukul

Related - https://github.com/family/connectkit/discussions/323

2023-12-13 10:07 UTC, anukul commented
cc @lochie

2024-02-15 01:39 UTC, lochie requested changes

2024-02-15 01:39 UTC, lochie commented on packages/connectkit/src/siwe/SIWEContext.tsx
> +  }) => Promise<string>;
This should allow for both `string | Promise<string>` to avoid breaking changes

2024-06-04 02:51 UTC, lochie commented
adding support for this in https://github.com/family/connectkit/pull/387

2024-06-04 02:51 UTC, closed without merging